---
- name: My playbook
  hosts: all
  vars:
    workspace: "{{ ('/temp', ansible_env.USER) | path_join }}"
    usr_dir: "{{ (workspace, 'usr') | path_join }}"
    tmp_dir: "{{ (workspace, 'tmp') | path_join }}"
    paths:
      - "{{ (usr_dir, 'bin') | path_join }}"
      - "{{ (ansible_env.HOME, '.local/bin') | path_join }}"
      - "{{ (ansible_env.HOME, '.local/usr/bin') | path_join }}"
      - "{{ ansible_env.PATH }}"
    pkg_config_paths:
      - "{{ (usr_dir, 'lib/pkgconfig') | path_join }}"
      - "{{ (usr_dir, 'lib/x86_64-linux-gnu/pkgconfig') | path_join }}"
  environment:
    PATH: "{{ paths | join(':') }}"
    PKG_CONFIG_PATH: "{{ pkg_config_paths | join(':') }}"
  tasks:
    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ usr_dir }}"
        - "{{ tmp_dir }}"

    - include_vars:
        name: urls
        file: urls.yml

    # TODO: do we have to install pkg-config as well?
    - block:
        - name: "Check GLib"
          command: pkg-config --libs glib-2.0

      rescue:
        - include_role:
            name: qemu
            tasks_from: glib.yml

    - block:
        - name: "Check Pixman"
          command: pkg-config --libs pixman-1

      rescue:
        - include_role:
            name: qemu
            tasks_from: pixman.yml

    - block:
        - name: "Check QEMU"
          command: which qemu-system-x86_64

      rescue:
        - include_role:
            name: qemu
            tasks_from: qemu.yml
