---
- name: My playbook
  hosts: all
  vars:
    workspace: "{{ ('/temp', ansible_env.USER) | path_join }}"
    usr_dir: "{{ (workspace, 'usr') | path_join }}"
    tmp_dir: "{{ (workspace, 'tmp') | path_join }}"
    paths:
      - "{{ (usr_dir, 'bin') | path_join }}"
      - "{{ (usr_dir, 'usr/bin') | path_join }}"
      - "{{ (ansible_env.HOME, '.local/bin') | path_join }}"
      - "{{ (ansible_env.HOME, '.local/usr/bin') | path_join }}"
      - "{{ ansible_env.PATH }}"
    pkg_config_paths:
      - "{{ (usr_dir, 'lib/pkgconfig') | path_join }}"
      - "{{ (usr_dir, 'lib/x86_64-linux-gnu/pkgconfig') | path_join }}"
      - "{{ (usr_dir, 'lib64/pkgconfig') | path_join }}"
  environment:
    PATH: "{{ paths | join(':') }}"
    PKG_CONFIG_PATH: "{{ pkg_config_paths | join(':') }}"
  tasks:
    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ usr_dir }}"
        - "{{ tmp_dir }}"

    - include_vars:
        name: urls
        file: urls.yml

    # TODO: do we have to install pkg-config as well?
    # https://gitlab.freedesktop.org/pkg-config/pkg-config

    - block:
        - name: "Check GLib"
          command: pkg-config --libs glib-2.0

      rescue:
        - include_role:
            name: qemu
            tasks_from: glib.yml

    - block:
        - name: "Check Pixman"
          command: pkg-config --libs pixman-1

      rescue:
        - include_role:
            name: qemu
            tasks_from: pixman.yml

    - block:
        - name: "Check QEMU"
          command: which qemu-system-x86_64

      rescue:
        - include_role:
            name: qemu
            tasks_from: qemu.yml

    - block:
        - name: "Check libcap2"
          command: pkg-config --libs libcap

      rescue:
        - include_role:
            name: cloud-utils
            tasks_from: libcap2.yml

    - block:
        - name: "Check bzip2"
          stat:
            path: "{{ (usr_dir, 'include/bzlib.h') | path_join }}"
          register: bzlib_st
          failed_when: not bzlib_st.stat.exists

      rescue:
        - include_role:
            name: cloud-utils
            tasks_from: bzip2.yml

    - block:
        - name: "Check cdrkit"
          command: which genisoimage

      rescue:
        - include_role:
            name: cloud-utils
            tasks_from: cdrkit.yml

    - block:
        - name: "Check cloud-utils"
          command: which cloud-localds

      rescue:
        - include_role:
            name: cloud-utils
            tasks_from: cloud-utils.yml

    - debug:
        msg: Please add "{{ usr_dir }}/bin:{{ usr_dir }}/usr/bin" to your PATH.
